export const questionSets = {
  1: {
    topic: "Travel & Adventure",
    questions: [
      "What is your favorite travel destination",
      "Which type of trip do you prefer",
      "How do you like to explore new places",
      "Which adventure activity excites you the most",
      "What is your go-to travel accessory",
      "What is your favorite mode of transportation",
      "Which cultural experience do you enjoy",
    ],
    options: [
      { A: "Mountains", B: "Beach", C: "City" },
      { A: "Relaxing", B: "Adventure", C: "Cultural" },
      { A: "Guided tours", B: "Self-exploration", C: "Local guides" },
      { A: "Skydiving", B: "Scuba diving", C: "Mountain climbing" },
      { A: "Camera", B: "Backpack", C: "Travel pillow" },
      { A: "Plane", B: "Train", C: "Car" },
      { A: "Food tasting", B: "Local festivals", C: "Museum visits" },
    ],
  },
  2: {
    topic: "Food & Cuisine",
    questions: [
      "What is your favorite cuisine",
      "Which dessert do you prefer",
      "What is your go-to comfort food",
      "Which cooking method do you like",
      "What is your favorite type of restaurant",
      "Which drink do you prefer with your meals",
      "What is your favorite street food",
    ],
    options: [
      { A: "Italian", B: "Chinese", C: "Mexican" },
      { A: "Ice cream", B: "Cake", C: "Cookies" },
      { A: "Pizza", B: "Burger", C: "Pasta" },
      { A: "Grilling", B: "Baking", C: "Stir-frying" },
      { A: "Fine dining", B: "Casual", C: "Fast food" },
      { A: "Water", B: "Wine", C: "Soda" },
      { A: "Tacos", B: "Hot dogs", C: "Churros" },
    ],
  },
  3: {
    topic: "Movies & TV Shows",
    questions: [
      "Which movie genre do you enjoy the most",
      "What is your favorite type of TV show",
      "Who is your favorite actor",
      "Which streaming service do you use",
      "What is your go-to movie snack",
      "Which type of TV series do you binge-watch",
      "Who is your favorite director",
    ],
    options: [
      { A: "Action", B: "Comedy", C: "Drama" },
      { A: "Sitcoms", B: "Reality TV", C: "Documentaries" },
      { A: "Leonardo DiCaprio", B: "Scarlett Johansson", C: "Dwayne Johnson" },
      { A: "Netflix", B: "Hulu", C: "Amazon Prime" },
      { A: "Popcorn", B: "Candy", C: "Nachos" },
      { A: "Crime", B: "Fantasy", C: "Romance" },
      { A: "Steven Spielberg", B: "Christopher Nolan", C: "Quentin Tarantino" },
    ],
  },
  4: {
    topic: "Music & Arts",
    questions: [
      "Which genre of music do you listen to",
      "Who is your favorite musician",
      "What is your preferred way to listen to music",
      "Which instrument do you like the most",
      "What is your favorite type of art",
      "Which art museum would you visit",
      "Who is your favorite painter",
    ],
    options: [
      { A: "Rock", B: "Pop", C: "Jazz" },
      { A: "Taylor Swift", B: "Drake", C: "Beyoncé" },
      { A: "Streaming", B: "Vinyl", C: "Live concerts" },
      { A: "Guitar", B: "Piano", C: "Drums" },
      { A: "Painting", B: "Sculpture", C: "Photography" },
      { A: "Louvre", B: "MoMA", C: "Tate Modern" },
      { A: "Van Gogh", B: "Picasso", C: "Monet" },
    ],
  },
  5: {
    topic: "Books & Literature",
    questions: [
      "What is your favorite genre of books",
      "Who is your favorite author",
      "Which book format do you prefer",
      "What is your go-to reading spot",
      "Which classic novel do you love",
      "What is your favorite book series",
      "Who is your favorite fictional character",
    ],
    options: [
      { A: "Mystery", B: "Romance", C: "Science Fiction" },
      { A: "J.K. Rowling", B: "Stephen King", C: "Agatha Christie" },
      { A: "Hardcover", B: "Paperback", C: "E-book" },
      { A: "Couch", B: "Bed", C: "Park" },
      { A: "Pride and Prejudice", B: "1984", C: "Moby Dick" },
      { A: "Harry Potter", B: "Lord of the Rings", C: "Game of Thrones" },
      { A: "Sherlock Holmes", B: "Katniss Everdeen", C: "Harry Potter" },
    ],
  },
  6: {
    topic: "Technology & Gadgets",
    questions: [
      "Which smartphone brand do you prefer",
      "What is your favorite social media app",
      "Which gadget can you not live without",
      "What is your favorite tech trend",
      "Which operating system do you use",
      "What is your favorite smart home device",
      "Which wearable tech do you like",
    ],
    options: [
      { A: "Apple", B: "Samsung", C: "Google" },
      { A: "Instagram", B: "Twitter", C: "TikTok" },
      { A: "Smartphone", B: "Laptop", C: "Tablet" },
      { A: "AI", B: "Blockchain", C: "VR/AR" },
      { A: "iOS", B: "Android", C: "Windows" },
      { A: "Smart speakers", B: "Smart lights", C: "Security cameras" },
      { A: "Smartwatch", B: "Fitness tracker", C: "VR headset" },
    ],
  },
  7: {
    topic: "Sports & Fitness",
    questions: [
      "Which sport do you enjoy the most",
      "Who is your favorite athlete",
      "What is your go-to workout",
      "Which fitness app do you use",
      "What is your favorite sports team",
      "Which type of exercise do you prefer",
      "What is your favorite sports event",
    ],
    options: [
      { A: "Soccer", B: "Basketball", C: "Tennis" },
      { A: "LeBron James", B: "Serena Williams", C: "Lionel Messi" },
      { A: "Running", B: "Yoga", C: "Weightlifting" },
      { A: "Strava", B: "Nike Training Club", C: "Fitbit" },
      {
        A: "Manchester United",
        B: "Los Angeles Lakers",
        C: "New York Yankees",
      },
      { A: "Cardio", B: "Strength training", C: "Flexibility exercises" },
      { A: "Olympics", B: "World Cup", C: "Super Bowl" },
    ],
  },
  8: {
    topic: "Social Media & Trends",
    questions: [
      "Which social media platform do you use the most",
      "Who is your favorite influencer",
      "What type of content do you enjoy",
      "Which viral challenge did you try",
      "What is your favorite meme",
      "Which social media feature do you like",
      "Who is your favorite YouTuber",
    ],
    options: [
      { A: "Facebook", B: "Instagram", C: "TikTok" },
      { A: "Kim Kardashian", B: "PewDiePie", C: "Charli D'Amelio" },
      { A: "Photos", B: "Videos", C: "Stories" },
      {
        A: "Ice Bucket Challenge",
        B: "Mannequin Challenge",
        C: "TikTok dances",
      },
      { A: "Doge", B: "Distracted Boyfriend", C: "Success Kid" },
      { A: "Stories", B: "Live streams", C: "Reels" },
      { A: "MrBeast", B: "Markiplier", C: "Lilly Singh" },
    ],
  },
  9: {
    topic: "Fashion & Style",
    questions: [
      "Which brand do you prefer for clothing",
      "What is your favorite fashion accessory",
      "What is your go-to outfit for a casual day",
      "Which season do you love dressing up for",
      "What is your favorite type of shoes",
      "Who is your style icon",
      "What is your favorite color to wear",
    ],
    options: [
      { A: "Nike", B: "Zara", C: "Gucci" },
      { A: "Watches", B: "Sunglasses", C: "Hats" },
      { A: "Jeans and t-shirt", B: "Dress", C: "Athleisure" },
      { A: "Summer", B: "Winter", C: "Fall" },
      { A: "Sneakers", B: "Boots", C: "Sandals" },
      { A: "Rihanna", B: "David Beckham", C: "Zendaya" },
      { A: "Black", B: "White", C: "Red" },
    ],
  },
  10: {
    topic: "Gaming & Entertainment",
    questions: [
      "Which gaming platform do you use",
      "Who is your favorite game character",
      "What is your favorite genre of games",
      "Which game do you play the most",
      "What is your go-to snack while gaming",
      "Which type of multiplayer mode do you prefer",
      "What is your favorite gaming franchise",
    ],
    options: [
      { A: "PlayStation", B: "Xbox", C: "PC" },
      { A: "Mario", B: "Master Chief", C: "Lara Croft" },
      { A: "RPG", B: "Shooter", C: "Puzzle" },
      { A: "Fortnite", B: "Minecraft", C: "Call of Duty" },
      { A: "Chips", B: "Candy", C: "Pizza" },
      { A: "Co-op", B: "Competitive", C: "MMO" },
      { A: "The Legend of Zelda", B: "Final Fantasy", C: "Resident Evil" },
    ],
  },
  11: {
    topic: "Hobbies & Interests",
    questions: [
      "Which hobby do you spend the most time on",
      "What is your favorite type of DIY project",
      "Which instrument would you like to learn",
      "What is your favorite type of outdoor activity",
      "Which indoor activity do you enjoy",
      "What is your favorite board game",
      "Which new hobby would you like to try",
    ],
    options: [
      { A: "Reading", B: "Gardening", C: "Crafting" },
      { A: "Home decor", B: "Painting", C: "Woodworking" },
      { A: "Guitar", B: "Piano", C: "Drums" },
      { A: "Hiking", B: "Cycling", C: "Picnicking" },
      { A: "Puzzles", B: "Video games", C: "Cooking" },
      { A: "Monopoly", B: "Chess", C: "Scrabble" },
      { A: "Pottery", B: "Knitting", C: "Photography" },
    ],
  },
  12: {
    topic: "Health & Wellness",
    questions: [
      "Which type of exercise do you prefer",
      "What is your favorite healthy snack",
      "Which wellness practice do you follow",
      "What is your go-to stress relief method",
      "Which fitness class do you enjoy",
      "What is your favorite way to relax",
      "Which health goal are you focusing on",
    ],
    options: [
      { A: "Yoga", B: "Running", C: "Weightlifting" },
      { A: "Fruit", B: "Nuts", C: "Smoothies" },
      { A: "Meditation", B: "Mindfulness", C: "Deep breathing" },
      { A: "Listening to music", B: "Exercise", C: "Reading" },
      { A: "Pilates", B: "Spin", C: "HIIT" },
      { A: "Watching TV", B: "Napping", C: "Spending time with friends" },
      { A: "Weight loss", B: "Muscle gain", C: "Better sleep" },
    ],
  },
  13: {
    topic: "Education & Learning",
    questions: [
      "Which subject did you enjoy the most in school",
      "What is your favorite way to learn new things",
      "Which online learning platform do you use",
      "What is your preferred study environment",
      "Which language would you like to learn",
      "What is your favorite type of book to read",
      "Which educational tool do you find most helpful",
    ],
    options: [
      { A: "Math", B: "History", C: "Science" },
      { A: "Reading books", B: "Watching videos", C: "Attending workshops" },
      { A: "Coursera", B: "Udemy", C: "LinkedIn Learning" },
      { A: "Library", B: "Coffee shop", C: "Home" },
      { A: "Spanish", B: "French", C: "Mandarin" },
      { A: "Biographies", B: "Self-help", C: "Fiction" },
      { A: "Flashcards", B: "Apps", C: "Study groups" },
    ],
  },
  14: {
    topic: "Personal Finance",
    questions: [
      "What is your approach to budgeting",
      "Which financial goal are you working towards",
      "What is your preferred method of saving money",
      "Which type of investment interests you",
      "What is your go-to finance app",
      "Which type of insurance do you prioritize",
      "Who is your favorite finance guru",
    ],
    options: [
      { A: "Strict budgeting", B: "Flexible budgeting", C: "No budgeting" },
      { A: "Retirement", B: "Debt repayment", C: "Buying a home" },
      { A: "High-yield savings", B: "Investments", C: "Cutting expenses" },
      { A: "Stocks", B: "Real estate", C: "Cryptocurrency" },
      { A: "Mint", B: "YNAB", C: "Personal Capital" },
      { A: "Health insurance", B: "Life insurance", C: "Car insurance" },
      { A: "Dave Ramsey", B: "Suze Orman", C: "Robert Kiyosaki" },
    ],
  },
  15: {
    topic: "Science & Nature",
    questions: [
      "Which area of science fascinates you the most",
      "What is your favorite natural phenomenon",
      "Which scientific discovery do you find most interesting",
      "What is your favorite type of ecosystem",
      "Who is your favorite scientist",
      "Which space mission do you find most exciting",
      "What is your favorite science documentary",
    ],
    options: [
      { A: "Astronomy", B: "Biology", C: "Physics" },
      { A: "Aurora Borealis", B: "Volcanoes", C: "Tornadoes" },
      { A: "DNA", B: "Gravity", C: "Quantum Mechanics" },
      { A: "Rainforest", B: "Desert", C: "Ocean" },
      { A: "Albert Einstein", B: "Marie Curie", C: "Isaac Newton" },
      { A: "Apollo 11", B: "Mars Rover", C: "Hubble Telescope" },
      { A: "Planet Earth", B: "Cosmos", C: "Blue Planet" },
    ],
  },
  16: {
    topic: "Automobiles & Transportation",
    questions: [
      "Which type of car do you prefer",
      "What is your favorite car brand",
      "Which mode of transportation do you use the most",
      "What is your favorite type of road trip",
      "Which car feature do you find most useful",
      "What is your favorite classic car",
      "Which electric vehicle would you choose",
    ],
    options: [
      { A: "Sedan", B: "SUV", C: "Convertible" },
      { A: "Toyota", B: "BMW", C: "Tesla" },
      { A: "Public transit", B: "Car", C: "Bike" },
      { A: "Scenic drives", B: "Cross-country", C: "Weekend getaway" },
      { A: "Navigation system", B: "Heated seats", C: "Sunroof" },
      { A: "Ford Mustang", B: "Chevrolet Camaro", C: "Volkswagen Beetle" },
      { A: "Tesla Model S", B: "Nissan Leaf", C: "Chevy Bolt" },
    ],
  },
  17: {
    topic: "Business & Economics",
    questions: [
      "Which type of business interests you the most",
      "Who is your favorite entrepreneur",
      "What is your preferred investment strategy",
      "Which economic trend do you find most concerning",
      "What is your favorite business book",
      "Which financial market do you follow",
      "What is your approach to personal finance",
    ],
    options: [
      { A: "Startups", B: "Corporations", C: "Small businesses" },
      { A: "Elon Musk", B: "Oprah Winfrey", C: "Warren Buffett" },
      { A: "Long-term investing", B: "Day trading", C: "Real estate" },
      { A: "Inflation", B: "Unemployment", C: "Recession" },
      {
        A: "The Lean Startup",
        B: "Rich Dad Poor Dad",
        C: "Think and Grow Rich",
      },
      { A: "Stock market", B: "Real estate", C: "Cryptocurrency" },
      { A: "Budgeting", B: "Saving", C: "Investing" },
    ],
  },
  18: {
    topic: "History & Culture",
    questions: [
      "Which historical period fascinates you the most",
      "Who is your favorite historical figure",
      "Which cultural festival would you like to attend",
      "What is your favorite historical documentary",
      "Which type of museum do you enjoy visiting",
      "What is your favorite historical site",
      "Which ancient civilization interests you the most",
    ],
    options: [
      { A: "Renaissance", B: "Medieval", C: "Ancient Egypt" },
      { A: "Cleopatra", B: "Alexander the Great", C: "Mahatma Gandhi" },
      { A: "Carnival", B: "Diwali", C: "Oktoberfest" },
      {
        A: "Ken Burns: Civil War",
        B: "The World at War",
        C: "Apocalypse: The Second World War",
      },
      { A: "Art", B: "Science", C: "History" },
      { A: "Machu Picchu", B: "Great Wall of China", C: "Pyramids of Giza" },
      { A: "Mayan", B: "Greek", C: "Roman" },
    ],
  },
  19: {
    topic: "Environment & Sustainability",
    questions: [
      "Which environmental issue concerns you the most",
      "What is your preferred method of reducing waste",
      "Which sustainable practice do you follow",
      "What is your favorite renewable energy source",
      "Which conservation effort do you support",
      "What is your favorite eco-friendly product",
      "Which type of sustainable travel do you prefer",
    ],
    options: [
      { A: "Climate change", B: "Deforestation", C: "Pollution" },
      { A: "Recycling", B: "Composting", C: "Reusing" },
      { A: "Reducing plastic use", B: "Saving water", C: "Energy efficiency" },
      { A: "Solar", B: "Wind", C: "Hydro" },
      {
        A: "Wildlife preservation",
        B: "Marine protection",
        C: "Forest conservation",
      },
      {
        A: "Reusable bags",
        B: "Eco-friendly cleaning products",
        C: "Bamboo toothbrush",
      },
      { A: "Eco-tourism", B: "Staycations", C: "Public transport" },
    ],
  },
  20: {
    topic: "Relationships & Family",
    questions: [
      "What is your favorite way to spend time with family",
      "Which type of family tradition do you cherish",
      "What is your go-to activity for date night",
      "How do you prefer to stay connected with friends",
      "Which type of gift do you like to give",
      "What is your favorite family vacation spot",
      "Which type of event do you enjoy with loved ones",
    ],
    options: [
      { A: "Family dinners", B: "Game nights", C: "Outdoor activities" },
      {
        A: "Holiday celebrations",
        B: "Weekend getaways",
        C: "Family reunions",
      },
      { A: "Dining out", B: "Movies", C: "Outdoor adventures" },
      { A: "Texting", B: "Calling", C: "Social media" },
      { A: "Personalized gifts", B: "Experience gifts", C: "Handmade gifts" },
      { A: "Beach", B: "Mountains", C: "Theme parks" },
      { A: "Birthdays", B: "Weddings", C: "Anniversaries" },
    ],
  },
  21: {
    topic: "Pets & Animals",
    questions: [
      "Which type of pet do you prefer",
      "What is your favorite animal",
      "Which pet activity do you enjoy the most",
      "How do you spoil your pet",
      "What is your favorite animal documentary",
      "Which exotic animal would you like to see",
      "What is your go-to pet care tip",
    ],
    options: [
      { A: "Dogs", B: "Cats", C: "Fish" },
      { A: "Elephant", B: "Lion", C: "Dolphin" },
      { A: "Walks", B: "Playtime", C: "Training" },
      { A: "Treats", B: "Toys", C: "Grooming" },
      { A: "March of the Penguins", B: "Blackfish", C: "The Blue Planet" },
      { A: "Pandas", B: "Koalas", C: "Penguins" },
      { A: "Regular vet visits", B: "Healthy diet", C: "Exercise" },
    ],
  },
  22: {
    topic: "Travel & Culture",
    questions: [
      "Which country would you like to visit",
      "What is your favorite cultural festival",
      "How do you prefer to experience a new city",
      "Which type of accommodation do you prefer",
      "What is your favorite travel season",
      "Which type of cuisine do you enjoy while traveling",
      "What is your favorite travel souvenir",
    ],
    options: [
      { A: "Japan", B: "Italy", C: "Brazil" },
      { A: "Carnival", B: "Diwali", C: "Oktoberfest" },
      { A: "Walking tours", B: "Bus tours", C: "Biking" },
      { A: "Hotel", B: "Airbnb", C: "Hostel" },
      { A: "Summer", B: "Winter", C: "Fall" },
      { A: "Street food", B: "Fine dining", C: "Local specialties" },
      { A: "Postcards", B: "Keychains", C: "Handmade crafts" },
    ],
  },
  23: {
    topic: "Lifestyle & Wellness",
    questions: [
      "What is your morning routine",
      "Which type of diet do you follow",
      "What is your favorite self-care activity",
      "How do you prefer to stay active",
      "What is your go-to relaxation technique",
      "Which hobby brings you the most joy",
      "What is your favorite way to unwind after a long day",
    ],
    options: [
      { A: "Meditation", B: "Exercise", C: "Coffee" },
      { A: "Vegan", B: "Keto", C: "Balanced" },
      { A: "Spa day", B: "Reading", C: "Meditation" },
      { A: "Gym workouts", B: "Outdoor activities", C: "Home workouts" },
      { A: "Breathing exercises", B: "Listening to music", C: "Watching TV" },
      { A: "Gardening", B: "Cooking", C: "Painting" },
      { A: "Taking a bath", B: "Watching a movie", C: "Reading a book" },
    ],
  },
  24: {
    topic: "Culture & Arts",
    questions: [
      "Which type of art do you appreciate the most",
      "Who is your favorite author",
      "What is your preferred type of live performance",
      "Which museum would you like to visit",
      "What is your favorite type of music",
      "Which cultural activity do you enjoy",
      "Who is your favorite historical figure",
    ],
    options: [
      { A: "Painting", B: "Sculpture", C: "Photography" },
      { A: "J.K. Rowling", B: "George Orwell", C: "J.R.R. Tolkien" },
      { A: "Theater", B: "Concerts", C: "Dance" },
      { A: "Louvre", B: "MoMA", C: "Tate Modern" },
      { A: "Classical", B: "Rock", C: "Jazz" },
      { A: "Food festivals", B: "Film festivals", C: "Art exhibitions" },
      { A: "Cleopatra", B: "Leonardo da Vinci", C: "Marie Curie" },
    ],
  },
  25: {
    topic: "Technology & Innovation",
    questions: [
      "Which tech gadget do you use the most",
      "What is your favorite social media app",
      "Which emerging technology excites you the most",
      "What is your preferred operating system",
      "Which smart home device do you find most useful",
      "What is your favorite type of wearable tech",
      "Which tech trend do you follow",
    ],
    options: [
      { A: "Smartphone", B: "Laptop", C: "Tablet" },
      { A: "Instagram", B: "Twitter", C: "TikTok" },
      { A: "AI", B: "Blockchain", C: "Augmented Reality" },
      { A: "iOS", B: "Android", C: "Windows" },
      { A: "Smart Speakers", B: "Smart Lights", C: "Smart Thermostat" },
      { A: "Smartwatch", B: "Fitness Tracker", C: "VR Headset" },
      { A: "5G", B: "Internet of Things", C: "Cybersecurity" },
    ],
  },
};
